### ISSUE TITLE
New directory generator based on experiment name

### ISSUE THREAD

**Issue by biobenkj** [mandel01/pyinseq#30]
Would it be worth automating a way to add like a '_1 or _2' (or even the date?) to the end of the experiment directory? Just warn the user that it exists and that the new one was created.

**Comment by mandel01** [comment]
I think a date plus increment here is a good idea. So options would be:

```
# don't add an increment (current setup + date)
experiment01_2016_03      # 1st run
[error on rerun]          # 2nd run or rerun on already_demultiplexed samples

# increment only if needed
experiment01_2016_03_01
experiment01_2016_03_01_run02

# always add an increment
experiment01_2016_03_01_run01
experiment01_2016_03_01_run02

# all of the above options with date first
2016_03_01_experiment01
2016_03_01_experiment01_run01
2016_03_01_experiment01_run02
```

I think I like some version of `always add an increment` because it's systematic but I don't think it matters too much. The most important is that the results be reproducible so each run needs to have enough information to rerun all of the dependent steps.

Two minor concerns to consider on implementation:
1. The folders can be large and this make is easier to make lots of them. Could consider adding a warning about size if the user's drive may not have enough space to handle the analysis comfortably.
2. As we look at ways to rerun demultiplexed samples (https://github.com/mandel01/pyinseq/issues/31) want to be sure users can reproduce their analyses if some are dependent on others. Not relevant now; will add comments in that issue.
