### ISSUE TITLE
test_pyinseq_genomeprep_script doesn't seem to work

### ISSUE THREAD

**Issue by mandel01** [mandel01/pyinseq#52]
Test passes even if the comparison directory is removed

**Comment by biobenkj** [comment]
Hi @mandel01! Without diving too much into the code, is it possible that the status returned by the runscript command in the test_utils.py is returning a 0 status because of the:

```
if directory:
    os.chdir(directory)
else:
    directory = cwd
```
Noticed the issue and am starting to play with the code (which looks great!) for someone getting ready to do INseq like work.

**Comment by mandel01** [comment]
Hi @biobenkj I think this fixed on github.

```
pip install git+git://github.com/mandel01/pyinseq
```

Will try to get it updated in PyPI in the next week. Glad it is useful! Send any other comments...

**Comment by mandel01** [comment]
Disregard that... digging into it now!

**Comment by mandel01** [comment]
The issue is that `filecmp.dircmp().diff_files` does not compare identities in subdirectories. This affects the integrity of other tests too. It just turns out to not be a big deal for the other tests because the top level files only get generated correctly if the subdirectories are right.

**Comment by mandel01** [comment]
Thanks @eburgoswisc for fixing this!!
